watchlist = [
        # NIFTY 50
        "ADANIENT.NS","ADANIPORTS.NS","APOLLOHOSP.NS","ASIANPAINT.NS","AXISBANK.NS",
        "BAJAJ-AUTO.NS","BAJFINANCE.NS","BAJAJFINSV.NS","BEL.NS","BHARTIARTL.NS",
        "CIPLA.NS","COALINDIA.NS","DRREDDY.NS","EICHERMOT.NS","EXIDEIND.NS",
        "GRASIM.NS","HCLTECH.NS","HDFCBANK.NS","HDFCLIFE.NS","HEROMOTOCO.NS",
        "HINDALCO.NS","HINDUNILVR.NS","ICICIBANK.NS","INDUSINDBK.NS","INFY.NS",
        "ITC.NS","JSWSTEEL.NS","KOTAKBANK.NS","LT.NS","M&M.NS",
        "MARUTI.NS","NESTLEIND.NS","NTPC.NS","ONGC.NS","POWERGRID.NS",
        "RELIANCE.NS","SBILIFE.NS","SBIN.NS","SUNPHARMA.NS","TCS.NS",
        "TATACONSUM.NS","TATAMOTORS.NS","TATASTEEL.NS","TECHM.NS","TITAN.NS",
        "ULTRACEMCO.NS","WIPRO.NS",

        # NIFTY Next 50
        "ABB.NS","ADANIENSOL.NS","ADANIGREEN.NS","ADANIPOWER.NS","AMBUJACEM.NS",
        "BAJAJHLDNG.NS","BAJAJHFL.NS","BANKBARODA.NS","BPCL.NS","BRITANNIA.NS",
        "BOSCHLTD.NS","CANBK.NS","CHOLAFIN.NS","DABUR.NS","DIVISLAB.NS",
        "DLF.NS","DMART.NS","GAIL.NS","GODREJCP.NS","HAVELLS.NS",
        "HAL.NS","HINDZINC.NS","ICICIGI.NS","ICICIPRULI.NS","INDHOTEL.NS",
        "IOC.NS","INDIGO.NS","IRFC.NS","JINDALSTEL.NS","JSWENERGY.NS",
        "LICI.NS","LTIM.NS","MOTHERSON.NS","NAUKRI.NS","PIDILITIND.NS",
        "PFC.NS","PNB.NS","RECLTD.NS","SHREECEM.NS","SIEMENS.NS",
        "TATAPOWER.NS","TORNTPHARM.NS","TVSMOTOR.NS","VEDL.NS","ZEEL.NS",
        "ZYDUSLIFE.NS",

        # NIFTY Midcap 50 (GMRINFRA, REC removed)
        "ALKEM.NS","ATUL.NS","AUBANK.NS","BALKRISIND.NS","BATAINDIA.NS",
        "BEL.NS","CUMMINSIND.NS","COROMANDEL.NS","COFORGE.NS","DIXON.NS",
        "ESCORTS.NS","GUJGASLTD.NS","GODREJPROP.NS","IDFCFIRSTB.NS",
        "INDIAMART.NS","JUBLFOOD.NS","LODHA.NS","LTTS.NS","MANAPPURAM.NS",
        "MRPL.NS","MPHASIS.NS","MUTHOOTFIN.NS","NHPC.NS","NMDC.NS",
        "PAGEIND.NS","PEL.NS","PIIND.NS","POLYCAB.NS","RAJESHEXPO.NS",
        "SRF.NS","SUNDARMFIN.NS","SUNTV.NS","THERMAX.NS",
        "TRENT.NS","TVSMOTOR.NS","UBL.NS","UNIONBANK.NS","VOLTAS.NS",
        "ZYDUSLIFE.NS","CANFINHOME.NS","DEEPAKNTR.NS","FEDERALBNK.NS","GLAND.NS",
        "GRINDWELL.NS","IIFL.NS","INDIANB.NS","IPCALAB.NS","JINDALSAW.NS"]
